# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHBoQ0p0qCVKwkH47vlJU7Deft2nZ0zn
"""

import streamlit as st
import time

# Page config
st.set_page_config(page_title="📝 Text Summarizer", layout="centered")

# App title
st.title("📝 Text Summarizer")
st.markdown("Enter your text below and select the desired summary length.")

# Text input
text_input = st.text_area(
    "Input Text",
    placeholder="Paste your text here...",
    height=200
)

# Summary length slider
summary_length = st.slider("Summary Length (words)", min_value=10, max_value=100, value=50)

# Caching function for performance
@st.cache_data
def slow_summarizer(text, length):
    time.sleep(2)  # Simulate processing time
    return " ".join(text.split()[:length])

# Action button
if st.button("Summarize"):
    if not text_input.strip():
        st.warning("Please input some text to summarize.")
    else:
        summary = slow_summarizer(text_input, summary_length)
        st.success(f"Here is your summary (first {summary_length} words):")
        st.write(summary)

# Optional footer
st.markdown("---")
st.caption("Built with ❤️ using Streamlit")